#[Info]

site_name: 猎人笔记
site_url: https://note.inuebisu.cn
site_author: inuEbisu
site_description: 犬戎的笔记

repo_url: https://github.com/inuEbisu/HuntersNotes
repo_name: inuEbisu/HuntersNotes
edit_uri: edit/main/docs

theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/favicon.ico
  custom_dir: overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: brown
      accent: indigo
      toggle:
        icon: material/weather-night
        name: 切换至深色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: 切换至浅色模式
  font:
    code: JetBrains Mono NL
  features:
    - announce.dismiss
    - navigation.instant
    - navigation.instant.progress
    # - header.autohide
    - navigation.tracking
    - navigation.tabs
    # - navigation.tabs.sticky
    # - navigation.sections
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - search.share
    # - navigation.expand
    - navigation.indexes
    - content.tabs.link
    - content.tooltips
    - content.code.copy
    - content.action.edit
    - content.action.view
    - content.code.annotate
    # - toc.integrate
    - toc.follow
  language: zh

plugins:
  - glightbox:
      width: 80%
      skip_classes:
        - off-glb
  - search:
      lang:
        - en
        - zh
  - offline
  - changelog
  - git-revision-date-localized:
      type: datetime
      timezone: Asia/Shanghai
      locale: zh
      enable_creation_date: true
  - statistics:
      page_check_metadata: comment
  - mkdocs-simple-hooks:
      hooks:
        on_page_markdown: "hooks.typst:on_page_markdown"
  # - heti:
  #     disable_serve: false

extra:
  analytics:
    provider: google
    property: G-Z6GN5WGV4F

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
  - https://gcore.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css
  - https://gcore.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css
  - https://gcore.jsdelivr.net/npm/jetbrains-mono@1.0.6/css/jetbrains-mono-nl.min.css
  - assets/css/custom.css
  - assets/css/card.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js
  - assets/js/katex.js

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 4
  - meta
  - def_list
  - attr_list
  - md_in_html
  - sane_lists
  - admonition
  - footnotes
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true

nav:
  - 主页:
      - index.md
  - 数理:
      - math_phys/index.md
      - 概率论与数理统计:
          - math_phys/probability/index.md
          - math_phys/probability/1.md
          - math_phys/probability/2.md
          - math_phys/probability/3.md
      - 大学物理（乙）II:
          - math_phys/phy2/index.md
      - 大学物理实验:
          - math_phys/phyexp/index.md
  - 计算机:
      - cs/index.md
      - 算法与数据结构:
          - 高级数据结构与算法分析:
              - cs/ds/ads/index.md
              - cs/ds/ads/lec6.md
              - cs/ds/ads/lec7.md
              - cs/ds/ads/lec8.md
      - 计算机系统:
          - 计算机组成:
              - cs/sys/organization/index.md
              - cs/sys/organization/ch1.md
              - cs/sys/organization/ch2.md
              - cs/sys/organization/env.md
          - "NJU 计算机系统基础":
              - cs/sys/njuicspa/index.md
              - cs/sys/njuicspa/pa0.md
              - cs/sys/njuicspa/pa1.md
          - "NJU 操作系统":
              - cs/sys/njuos/index.md
      - 人工智能:
          - "CMU 10-414/714 Deep Learning Systems":
              - cs/ai/dlsys/index.md
      - 高性能计算:
          - "HPC101 超算短学期":
              - cs/hpc/hpc101/index.md
              - cs/hpc/hpc101/riscv.md
              - cs/hpc/hpc101/llm.md
      - 编程语言:
          - cs/pl/c_smallbig.md
  - CTF:
      - ctf/index.md
      - 比赛题解:
          - ctf/zjuctf2025.md
  - 工具:
      - tools/index.md
      - tools/mkdocs.md
      - tools/writing.md
  - 杂项:
      - misc/index.md
      - 律制:
          - misc/intonation/index.md
          - misc/intonation/ch01.md
          - misc/intonation/ch02.md
          - misc/intonation/ch03.md